repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
- repo: https://github.com/fastai/nbdev
  rev: 2.3.7
  hooks:
  - id: nbdev_clean
  - id: nbdev_export