"""Methods to generate anchor boxes of different aspect ratios.

Docs: https://thatgeeman.github.io/pybx/anchor.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_anchor.ipynb.

# %% auto #0
__all__ = [
    "MatchResult",
    "bx",
    "bxs",
    "get_gt_thresh_iou",
    "get_gt_max_iou",
    "get_gt_offsets",
]

# %% ../nbs/00_anchor.ipynb #642b16c6
import inspect
from dataclasses import dataclass

import math
import numpy as np
from fastcore.foundation import L, mask2idxs
from fastcore.utils import gt, is_listy
from numpy.typing import ArrayLike
from typing import Union
import json
from collections import defaultdict
import warnings

from .ops import named_idx
from .basics import get_bx, stack_bxs_inplace, BX_TYPE, BaseBx, Bx, bbx, get_bx
from .utils import get_edges, validate_boxes, as_tuple, reassign_label
from .excepts import NoGroundTruthBxs


@dataclass
class MatchResult:
    """Structured output from ground-truth/anchor matching.

    `box_ids` preserves the identity and input order of every ground-truth box.
    The remaining mappings use those same IDs as keys. Tuple unpacking and
    integer indexing expose `(matched_boxes, ious, masks)` for compatibility.
    """

    box_ids: tuple
    anchor_indices: dict
    ious: dict
    masks: dict
    matched_boxes: dict

    def __iter__(self):
        return iter((self.matched_boxes, self.ious, self.masks))

    def __getitem__(self, index):
        return (self.matched_boxes, self.ious, self.masks)[index]


def _resolve_box_ids(n_boxes, box_ids=None):
    """Return one unique, hashable identifier per ground-truth box."""
    if box_ids is None:
        return list(range(n_boxes))
    if isinstance(box_ids, (str, int, np.integer)):
        box_ids = [box_ids]
    else:
        box_ids = list(box_ids)
    if len(box_ids) != n_boxes:
        raise ValueError(
            f"Expected one box_id per ground-truth box, got {len(box_ids)} "
            f"IDs for {n_boxes} boxes."
        )
    try:
        unique_ids = set(box_ids)
    except TypeError as exc:
        raise TypeError("box_ids must be hashable.") from exc
    if len(unique_ids) != n_boxes:
        raise ValueError("box_ids must be unique.")
    return box_ids


def _pairwise_iou(boxes, anchors):
    """Calculate the complete box-by-anchor IoU matrix with NumPy."""
    boxes = np.asarray(boxes, dtype=float).reshape(-1, 4)
    anchors = np.asarray(anchors, dtype=float).reshape(-1, 4)
    top_left = np.maximum(boxes[:, None, :2], anchors[None, :, :2])
    bottom_right = np.minimum(boxes[:, None, 2:], anchors[None, :, 2:])
    intersection_sides = np.clip(bottom_right - top_left, 0, None)
    intersection = intersection_sides[..., 0] * intersection_sides[..., 1]
    box_sides = boxes[:, 2:] - boxes[:, :2]
    anchor_sides = anchors[:, 2:] - anchors[:, :2]
    box_areas = box_sides[:, 0] * box_sides[:, 1]
    anchor_areas = anchor_sides[:, 0] * anchor_sides[:, 1]
    union = box_areas[:, None] + anchor_areas[None, :] - intersection
    return np.divide(
        intersection,
        union,
        out=np.zeros_like(intersection, dtype=float),
        where=union > 0,
    )


# %% ../nbs/00_anchor.ipynb #c881e876
def bx(
    image_sz: (int, tuple),
    feature_sz: (int, tuple),
    asp_ratio: float = None,
    clip: bool = True,
    named: bool = True,
    anchor_sfx: str = "a",
    min_visibility: float = 0.25,
) -> ArrayLike:
    """Calculate anchor box coords given an image size and feature size
    for a single aspect ratio.

    Parameters
    ----------
    image_sz : (int,tuple)
        image size (width, height)
    feature_sz : (int,tuple)
        feature map size (width, height)
    asp_ratio : float, optional
        aspect ratio (width:height), by default None
    clip : bool, optional
        whether to apply np.clip, by default True
    named : bool, optional
        whether to return (coords, labels), by default True
    anchor_sfx : str, optional
        suffix anchor label with anchor_sfx, by default "a"
    min_visibility : float, optional
        minimum visibility dictates the condition for a box to be considered
        valid. The value corresponds to the ratio of expected area of an anchor box
        to the calculated area after clipping to image dimensions., by default 0.25

    Returns
    -------
    ArrayLike
        anchor box coordinates in `pascal_voc` format
        if named=True, a list of anchor box labels are also returned.
    """
    labels = None
    image_sz = as_tuple(image_sz)
    feature_sz = as_tuple(feature_sz)
    asp_ratio = 1.0 if asp_ratio is None else asp_ratio
    # n_boxes = __mul__(*feature_sz)
    top_edges = get_edges(image_sz, feature_sz, op="noop")
    bot_edge = get_edges(image_sz, feature_sz, op="add")
    coords = np.hstack([top_edges, bot_edge])  # raw coords
    coords_wh = coords[:, 2:] - coords[:, :2]  # w -> xmax-xmin, h -> ymax-ymin
    coords_center = coords[:, 2:] - coords_wh / 2  # xmax-w/2, ymax-h/2
    # scale the dimension of width and height with asp ratios
    _w = coords_wh[:, 0] * math.sqrt(asp_ratio)
    _h = coords_wh[:, 1] / math.sqrt(asp_ratio)
    coords_asp_wh = np.stack([_w, _h], -1)
    xy_min = coords_center - coords_asp_wh / 2
    xy_max = coords_center + coords_asp_wh / 2
    coords = np.hstack([xy_min, xy_max])
    # check for valid boxes
    b = validate_boxes(
        coords, image_sz, feature_sz, clip=clip, min_visibility=min_visibility
    )
    if named:
        anchor_sfx = f"{anchor_sfx}_{feature_sz[0]}x{feature_sz[1]}_{asp_ratio:.1f}_"
        labels = named_idx(len(b), anchor_sfx)
    # init multibx
    b = get_bx(
        b,
        labels,
    )
    return (b.coords, b.label) if named else b.coords


# %% ../nbs/00_anchor.ipynb #6620aaf3
def bxs(
    image_sz: (int, tuple),
    feature_szs: list = None,
    asp_ratios: list = None,
    named: bool = True,
    **kwargs,
) -> ArrayLike:
    """Calculate anchor box coords given an image size and multiple
    feature sizes for mutiple aspect ratios.

    Parameters
    ----------
    image_sz : (int,tuple)
        image size (width, height)
    feature_szs : list, optional
        list of feature map sizes, each feature map size being an int or tuple, by default [(8, 8), (2, 2)]
    asp_ratios : list, optional
        list of aspect ratios for anchor boxes, each aspect ratio being a float calculated by (width:height), by default [1 / 2.0, 1.0, 2.0]
    named : bool, optional
        whether to return (coords, labels), by default True

    Returns
    -------
    ArrayLike
        anchor box coordinates in pascal_voc format
        if named=True, a list of anchor box labels are also returned.
    """
    image_sz = as_tuple(image_sz)
    feature_szs = [8, 2] if feature_szs is None else feature_szs
    feature_szs = [as_tuple(fsz) for fsz in feature_szs]
    asp_ratios = [1 / 2.0, 1.0, 2.0] if asp_ratios is None else asp_ratios
    # always named=True for bx() call. named=True in fn signature of bxs() is in its scope.
    coords_ = [
        bx(image_sz, f, ar, named=True, **kwargs)
        for f in feature_szs
        for ar in asp_ratios
    ]
    coords_, labels_ = L(zip(*coords_))
    coords_ = np.vstack(coords_)
    labels_ = L([l_ for lab_ in labels_ for l_ in lab_])
    return (coords_, labels_) if named else np.vstack(coords_)


# %% ../nbs/00_anchor.ipynb #73bbd4a8
def get_gt_thresh_iou(
    true_annots,
    anchor_boxes,
    anchor_labels=None,
    iou_thresh=0.3,
    return_ious=False,
    return_masks=False,
    update_labels=True,
    box_ids=None,
):
    """Find positive anchors for each ground-truth box using an IoU threshold.

    Can result in an uneven number of positive anchors per ground-truth box.
    Matching is independent for each ground-truth box, so an anchor may match
    more than one object. IoUs are calculated as one vectorized matrix and
    returned at full floating-point precision.

    Args:
        true_annots (Any): True annotations, typically in `pascal_voc` format
        anchor_boxes (Any): Candidate anchor boxes, typically calculated with `pybx.bxs`
        anchor_labels (List, optional): Anchor box labels, will be overwritten with true labels if `update_labels=True`. Defaults to None.
        iou_thresh (float, optional): IOU threshold to filter out negative ground truth anchor boxes. Defaults to 0.3.
        return_ious (bool, optional): Return IOU values for selected positive ground truth anchor boxes. Defaults to False.
        return_masks (bool, optional): Return boolean masks for all anchor boxes indicating if a box is positive (`True`) or negative (`False`) ground truth box. Defaults to False.
        update_labels (bool, optional): Overwrite with true annotations. Defaults to True.
        box_ids (Iterable, optional): Unique identifiers for the ground-truth boxes. Defaults to their zero-based input positions.

    Returns:
        MatchResult: Box IDs, selected anchor indices, optional IoUs and masks,
        and matched boxes. Every mapping is keyed by the IDs in `box_ids`.
    """
    gt_anchors_per_box = {}
    anchor_indices_per_box = {}
    iou_per_box = {}
    mask_per_box = {}
    true_annots_as_bx = (
        get_bx(true_annots) if not isinstance(true_annots, BX_TYPE) else true_annots
    )
    box_ids = _resolve_box_ids(len(true_annots_as_bx), box_ids)
    anchor_labels = (
        [f"bx_{i}" for i in range(len(anchor_boxes))]
        if anchor_labels is None
        else anchor_labels
    )
    coords_as_bx = (
        get_bx(coords=anchor_boxes, label=anchor_labels)
        if not isinstance(anchor_boxes, BX_TYPE)
        else anchor_boxes
    )
    iou_matrix = _pairwise_iou(
        true_annots_as_bx.coords_as_numpy, coords_as_bx.coords_as_numpy
    )
    mask_matrix = iou_matrix >= iou_thresh

    for row_idx, (box_id, annots) in enumerate(zip(box_ids, true_annots_as_bx)):
        label = annots.label[0]  # is a list of len 1
        ious = iou_matrix[row_idx]
        mask = L(mask_matrix[row_idx].tolist())
        ious_filter = np.flatnonzero(mask_matrix[row_idx]).tolist()
        anchor_indices_per_box[box_id] = ious_filter

        if mask.sum() < 1:
            warnings.warn(
                NoGroundTruthBxs(
                    f"No good ground truth anchors found for label={label}, try lowering threshold (iou_thresh={iou_thresh} or increasing candidates."
                )
            )
            gt_anchors_per_box[box_id] = None

        if return_ious:
            # report filtered box IOUs
            iou_per_box[box_id] = L(ious[ious_filter].tolist())
        if return_masks:
            mask_per_box[box_id] = mask
        # report selected boxes
        # print([coords_as_bx[i] for i in ious_filter])
        if mask.sum() > 0:
            gt_anchors_per_box[box_id] = stack_bxs_inplace(
                *[
                    (
                        reassign_label(coords_as_bx[i], label=[label])
                        if update_labels
                        else coords_as_bx[i]
                    )
                    for i in ious_filter
                ]
            )

    return MatchResult(
        box_ids=tuple(box_ids),
        anchor_indices=anchor_indices_per_box,
        ious=iou_per_box,
        masks=mask_per_box,
        matched_boxes=gt_anchors_per_box,
    )


# %% ../nbs/00_anchor.ipynb #50723c9c
def get_gt_max_iou(
    true_annots,
    anchor_boxes,
    anchor_labels=None,
    return_ious=False,
    return_masks=False,
    positive_boxes=1,
    update_labels=True,
    box_ids=None,
):
    """Find the highest-IoU anchors for each ground-truth box.

    Selects up to `positive_boxes` distinct anchors for each ground-truth box.
    Matching is independent for each ground-truth box, so an anchor may match
    more than one object. IoUs and rankings are calculated as vectorized NumPy
    operations, and IoUs are returned at full floating-point precision.

    Args:
        true_annots (Any): True annotations, typically in `pascal_voc` format
        anchor_boxes (Any): Candidate anchor boxes, typically calculated with `pybx.bxs`
        anchor_labels (List, optional): Anchor box labels, will be overwritten with true labels if `update_labels=True`. Defaults to None.
        return_ious (bool, optional): Return IOU values for selected positive ground truth anchor boxes. Defaults to False.
        return_masks (bool, optional): Return boolean masks for all anchor boxes indicating if a box is positive (`True`) or negative (`False`) ground truth box. Defaults to False.
        update_labels (bool, optional): Overwrite with true annotations. Defaults to True.
        positive_boxes (int, optional): Number of extra/positive ground truth boxes to return. Defaults to 1.
        box_ids (Iterable, optional): Unique identifiers for the ground-truth boxes. Defaults to their zero-based input positions.

    Returns:
        MatchResult: Box IDs, selected anchor indices, optional IoUs and masks,
        and matched boxes. Every mapping is keyed by the IDs in `box_ids`.
    """
    if not isinstance(positive_boxes, (int, np.integer)) or isinstance(
        positive_boxes, bool
    ):
        raise TypeError("positive_boxes must be an integer.")
    if positive_boxes < 1:
        raise ValueError("positive_boxes must be at least 1.")
    gt_anchors_per_box = {}
    anchor_indices_per_box = {}
    iou_per_box = {}
    mask_per_box = {}
    true_annots_as_bx = (
        get_bx(true_annots) if not isinstance(true_annots, BX_TYPE) else true_annots
    )
    box_ids = _resolve_box_ids(len(true_annots_as_bx), box_ids)
    anchor_labels = (
        [f"bx_{i}" for i in range(len(anchor_boxes))]
        if anchor_labels is None
        else anchor_labels
    )
    coords_as_bx = (
        get_bx(coords=anchor_boxes, label=anchor_labels)
        if not isinstance(anchor_boxes, BX_TYPE)
        else anchor_boxes
    )
    n_boxes = len(coords_as_bx)
    iou_matrix = _pairwise_iou(
        true_annots_as_bx.coords_as_numpy, coords_as_bx.coords_as_numpy
    )
    n_positive = min(int(positive_boxes), n_boxes)
    ranked_anchor_indices = np.argsort(-iou_matrix, axis=1, kind="stable")[
        :, :n_positive
    ]

    for row_idx, (box_id, annots) in enumerate(zip(box_ids, true_annots_as_bx)):
        label = annots.label[0]  # is a list of len 1
        ious = iou_matrix[row_idx]
        ious_filter = ranked_anchor_indices[row_idx].tolist()
        anchor_indices_per_box[box_id] = ious_filter
        mask_array = np.zeros(n_boxes, dtype=bool)
        mask_array[ious_filter] = True
        mask = L(mask_array.tolist())

        if mask.sum() < 1:
            warnings.warn(
                NoGroundTruthBxs(
                    f"No good ground truth anchors found for label={label}, try increasing candidates."
                )
            )
            gt_anchors_per_box[box_id] = None

        if return_ious:
            # report filtered box IOUs
            iou_per_box[box_id] = L(ious[ious_filter].tolist())
        if return_masks:
            mask_per_box[box_id] = mask
        # report selected boxes
        # print([coords_as_bx[i] for i in ious_filter])
        if mask.sum() > 0:
            gt_anchors_per_box[box_id] = stack_bxs_inplace(
                *[
                    (
                        reassign_label(coords_as_bx[i], label=[label])
                        if update_labels
                        else coords_as_bx[i]
                    )
                    for i in ious_filter
                ]
            )

    return MatchResult(
        box_ids=tuple(box_ids),
        anchor_indices=anchor_indices_per_box,
        ious=iou_per_box,
        masks=mask_per_box,
        matched_boxes=gt_anchors_per_box,
    )


# %% ../nbs/00_anchor.ipynb #f3edab56
def get_gt_offsets(
    true_annots: BaseBx,
    anchor_boxes,
    anchor_labels=None,  # do we need to pass this
    masks=None,
    sigma=(0.1, 0.2),
    normalize=True,
    log_func=np.log,
    update_labels=False,
):
    """
    Calculates the offset of the true annotations from the anchor boxes using the `get_offset` method of `BaseBx`.

    Args:
        true_annots (Any): True annotation for a single object, typically in `pascal_voc` format
        anchor_boxes (Any): Candidate anchor boxes, typically calculated with `pybx.bxs`
        anchor_labels (List, optional): Anchor box labels, will be overwritten with ground truth labels if `update_labels=True`. Defaults to None.
        masks (List, optional): Anchor box masks indicating if a box is positive/negative anchor box. If nothing is passed, offsets are calculated for all anchor boxes passed. Defaults to None.
        sigma (tuple, optional): Estimated of standard deviation for the distances and ratios. Defaults to (0.1, 0.2).
        normalize (bool, optional): Whether to normalize the offsets using the methods used in the SSD paper. Defaults to True.
        log_func (func, optional): Function for normalizing the ratio of widths and heights. Defaults to np.log.
        update_labels (bool, optional): Overwrite positive anchor boxes with object class and negative anchor boxes with `background` class. Defaults to False.

    Returns:
        list: List of all anchor box offsets.
        list: List of corresponding anchor box labels.
    """
    if not isinstance(true_annots, Bx):
        # the annotation for a single object, make listy if not
        true_annots = true_annots if is_listy(true_annots) else [true_annots]
        true_annots = get_bx(true_annots)[0]  # get back the BaseBx

    n_anchors = len(anchor_boxes)
    # no of anchor boxes (includes positive and negative anchor boxes)
    masks = (
        masks if masks is not None else L([True] * n_anchors)
    )  # if no masks provided, repeat for all anchors
    offsets = np.zeros((n_anchors, 4))
    labels = L(["background"] * n_anchors)  # if update_labels else anchor_labels
    true_label = true_annots.label[0] if len(true_annots.label) != 0 else "unknown"
    for idx, (box, mask) in enumerate(zip(anchor_boxes, masks)):
        if mask:
            offsets[idx, :] = true_annots.get_offset(
                box, normalize=normalize, sigma=sigma, log_func=log_func
            )
            # labels with mask=True will be the candidates for actual ground truth class.
            if update_labels:  # and (labels is not None):
                labels[idx] = true_label
    return offsets, labels
