# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_excepts.ipynb.

# %% auto 0
__all__ = ['NoIntersection', 'BxViolation']

# %% ../nbs/02_excepts.ipynb 2
__all__ = ["NoIntersection", "BxViolation"]


class NoIntersection(Exception):
    """No intersection of boxes occur."""

    pass


class BxViolation(SyntaxWarning):
    """Violation of Bx properties."""

    pass

