# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_excepts.ipynb.

# %% auto 0
__all__ = ['NoIntersection', 'BxViolation']

# %% ../nbs/06_excepts.ipynb 2
__all__ = ["NoIntersection", "BxViolation"]

# %% ../nbs/06_excepts.ipynb 3
class NoIntersection(Exception):
    """No intersection of boxes occur."""

    pass


class BxViolation(SyntaxWarning):
    """Violation of Bx properties."""

    pass

