"""Docs: https://thatgeeman.github.io/pybx/excepts.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_excepts.ipynb.

# %% auto #0
__all__ = ['NoIntersection', 'BxViolation', 'NoGroundTruthBxs']

# %% ../nbs/06_excepts.ipynb #5082c22a
__all__ = ["NoIntersection", "BxViolation"]

# %% ../nbs/06_excepts.ipynb #7df203b1
class NoIntersection(Exception):
    """No intersection of boxes occur."""

    pass


class BxViolation(SyntaxWarning):
    """Violation of Bx properties."""

    pass

class NoGroundTruthBxs(SyntaxWarning):
    """No Ground Truth boxes found."""

    pass
